### ISSUE TITLE
String format in view_cart event

### ISSUE THREAD

**Issue by aligorhan** [tlamedia/gtm-kit#85] opened 2023-02-28 01:24 UTC
**When we turn off the tax option, view_cart's value turns to "string" format. i added plus (+) sign for convert number - float. Is it temporary solution? 😄**

![dd](https://user-images.githubusercontent.com/78086791/221727223-ac846e99-f612-4982-8e27-25785ce3b507.png)
![with - tax](https://user-images.githubusercontent.com/78086791/221727228-3931ec9b-70e6-4224-8e06-0830e1d9a8b1.png)
![without - tax](https://user-images.githubusercontent.com/78086791/221727233-41b22a15-d838-431c-9060-afa49370c3f9.png)

**Comment by TorbenLundsgaard** [comment] 2023-02-28 09:36
I can't reproduce the problem, but I have made a PR to type cast the value to float. Please test it and let me know if it fixes the problem.

`'value' => (float) $item['price']`

**Comment by aligorhan** [comment] 2023-02-28 12:03
hello thank you. 'value' => (float) $item['price'] didn't work, that showed value like this --> 0,
but i added this --> 'value'    => (float)$cart_value, and it worked.

**Comment by TorbenLundsgaard** [comment] 2023-02-28 12:24
Glad to hear it works. The bugfix will be included in the next release.

**Closed** 2023-02-28 12:24 UTC
